export enum EmailTemplates {
  WELCOME = 'WELCOME',
}

export enum Roles {
  ADMIN = 'Admin',
  APP_OWNER = 'AppOwner',
  APP_USER = 'AppUser',
  SUPER_ADMIN = 'SuperAdmin',
  SALESPERSON = 'Salesperson',
}

export const fontList = [
  "Alegreya",
  "Alegreya Sans",
  "Archivo Narrow",
  "BioRhyme",
  "Cardo",
  "Chivo",
  "Cormorant",
  "DM Sans",
  "Eczar",
  "Fira Sans",
  "IBM Plex Sans",
  "Inconsolata",
  "Inknut Antiqua",
  "Inter",
  "Karla",
  "Lato",
  "Libre Baskerville",
  "Libre Franklin",
  "Lora",
  "Manrope",
  "Merriweather",
  "Montserrat",
  "Neuton",
  "Open Sans",
  "Playfair Display",
  "Poppins",
  "Proza Libre",
  "PT Sans",
  "PT Serif",
  "Raleway",
  "Roboto",
  "Roboto Slab",
  "Rubik",
  "Space Grotesk",
  "Space Mono",
  "Spectral",
  "Source Sans Pro",
  "Source Serif Pro",
  "Syne",
  "Work Sans",
]
