-- AlterTable
ALTER TABLE "User" ADD COLUMN     "android_applink" VARCHAR(255),
ADD COLUMN     "app_banner" VARCHAR(255),
ADD COLUMN     "app_icon" VARCHAR(255),
ADD COLUMN     "app_name" VARCHAR(255),
ADD COLUMN     "business_name" VARCHAR(255),
ADD COLUMN     "checklist" VARCHAR(255),
ADD COLUMN     "domain" VARCHAR(255),
ADD COLUMN     "firebase_app_id" VARCHAR(255),
ADD COLUMN     "goal" VARCHAR(255),
ADD COLUMN     "industry_id" VARCHAR(30),
ADD COLUMN     "industry_other" VARCHAR(255),
ADD COLUMN     "ios_applink" VARCHAR(255),
ADD COLUMN     "is_show_logo" VARCHAR(255),
ADD COLUMN     "logo" VARCHAR(255),
ADD COLUMN     "mobile_template" VARCHAR(255),
ADD COLUMN     "redirect_url" VARCHAR(255),
ADD COLUMN     "social_media" VARCHAR(255),
ADD COLUMN     "social_media_handler_name" VARCHAR(255),
ADD COLUMN     "subscription_id" VARCHAR(30),
ADD COLUMN     "terms_of_service" VARCHAR(255),
ADD COLUMN     "trainer_created_by" VARCHAR(30),
ADD COLUMN     "trainer_id" VARCHAR(255),
ADD COLUMN     "unique_id" VARCHAR(50),
ADD COLUMN     "web_applink" VARCHAR(255),
ADD COLUMN     "website" VARCHAR(255);
